# Generated by Django 3.1.5 on 2021-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('pedido', models.TextField(max_length=100)),
                ('valor', models.FloatField()),
                ('qtd', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('pagamento', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=100)),
                ('qtd', models.IntegerField(default=0)),
                ('valor', models.CharField(max_length=20)),
                ('promocao', models.CharField(default=0, max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
